version: "3.8"

services:
  db:
    build: ./db
    container_name: postgres_12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emtct
    ports:
      - "5432:5432"

  test_db:
    build: ./db
    container_name: postgres_test_12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emtct
    ports:
      - "5432:5432"
